#!/bin/bash -e

function errorReturn() {
	return 1
}

function dims() {
	# NAME	
	# 	dims - Give the dimensions (rows and columns) of a given matrix
	# SYNOPSIS
	# 	Generates rows and columns of a given matrix in a file
	# DESCRIPTION
	# 	TODO
	# AUTHOR
	# 	TODO

	ROWS=$(wc -l < $1) # Counts the number of lines in the file with the matrix, which if formatted correctly will correspond to the number of rows
		
	words=$(wc -w < $1) # Counts the number of words in the file with the matrix
	COLS=$((words / ROWS)) # Divide the number of words by the number of rows to get columns

	echo $ROWS $COLS
	rm -f $1 # Delete temporary file
	return 0
}

function transpose() {

	tempfile="tempfile$$"
	rows=$(wc -l < $1)
	words=$(wc -w < $1)
	cols=$((words / rows))

	for ((i=1; i<=cols; i++)); do
		echo "$(cut -f $i $1)" > "$tempfile"
		echo "$(paste -s "$tempfile")" > "$tempfile"
		cat "$tempfile"
	done

	rm -f $1 $tempfile # Delete the temp files
	return 0
}

# MAIN PROG:

# Routes to different functions based on first arg value:
if [ "$1" = "dims" ] #If first arg is dims, call dims function
then
	datafilepath="datafile$$" # Generate a random file
	if [ "$#" = "1" ] # If the number of args is equal to one then read input from stdin into the random file
	then
		cat > "$datafilepath"
	elif [ "$#" = "2" ] # If number of args is two then assign the passed file to the random file
	then
		if [[ -r $2 ]]
		then
			datafilepath=$2
		else 
			>&2 echo The file you gave is not readable
			errorReturn
		fi
	else
		>&2 echo You did not pass the correct number of arguments
		errorReturn
	fi
	dims $datafilepath
elif [ "$1" = "transpose" ]
then
	datafilepath="datafile$$"
	if [ "$#" = "1" ]
	then
		cat > "$datafilepath"
	elif [ "$#" = "2" ]
	then
		if [[ -r $2 ]]
		then
			datafilepath=$2
		else
			>&2 echo The file you gave is not readable
			errorReturn
		fi

	else 
		>&2 echo You did not pass the correct number of arguments
		errorReturn
	fi
	transpose $datafilepath
elif [ "$1" = "mean" ]
then
	datafilepath="datafile$$"
	if [ "$#" = "1" ]
	then
		cat > "$datafilepath"
	elif [ "$#" = "2" ]
	then
		if [[ -r $2 ]]
		then
			datafilepath=$2
		else
			>&2 echo The file you gave is not readable
			errorReturn
		fi
	else 
		>&2 echo You did not pass the correct number of arguments
		errorReturn
	fi
	# mean $datafilepath
elif [ "$1" = "add" ]
then
	datafilepath1="datafile$$"
	datafilepath2="datafile$$"
	if [ "$#" = "3" ]
	then
		if [[ -r $2 && -r $3 ]]
		then
			datafilepath1=$2
			datafilepath2=$3
		else
			>&2 echo The file you gave is not readable
			errorReturn
		fi
	else
		>&2 echo You did not pass the correct number of arguments
		errorReturn
	fi
	# add $datafilepath1 $datafilepath2
elif [ "$1" = "multiply" ]
then
	datafilepath1="datafile$$"
	datafilepath2="datafile$$"
	if [ "$#" = "3" ]
	then
		if [[ -r $2 && -r $3 ]]
		then
			datafilepath1=$2
			datafilepath2=$3
		else
			>&2 echo The file you gave is not readable
			errorReturn
		fi
	else
		>&2 echo You did not pass the correct number of arguments
		errorReturn
	fi
	# multiply $datafilepath1 $datafilepath2
else 
	>&2 echo Command not recognized
	errorReturn	
fi
